"""empty message

Revision ID: 5d83972865c7
Revises: 39e273132f54
Create Date: 2024-04-03 20:07:55.037476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d83972865c7'
down_revision = '39e273132f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
