"""empty message

Revision ID: d9d08755bd93
Revises: b979ac92ff9e
Create Date: 2024-03-29 02:17:41.862005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d08755bd93'
down_revision = 'b979ac92ff9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
