"""empty message

Revision ID: dc64718a96a9
Revises: 5d83972865c7
Create Date: 2024-04-05 17:54:33.221949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc64718a96a9'
down_revision = '5d83972865c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa', schema=None) as batch_op:
        batch_op.drop_column('uid')

    # ### end Alembic commands ###
